execute pathogen#infect()
syntax on
set nu
set expandtab
set tabstop=2
set mouse=a
let mapleader = ','
map <leader>l :Align
nmap <leader>a :Ag<space>
nmap <leader>b :CtrlPBuffer<CR>
nmap <leader>d :NERDTreeToggle<CR>
nmap <leader>f :NERDTreeFind<CR>
nmap <leader>t :CtrlP<CR>
nmap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
nmap <leader>] :TagbarToggle<CR>
" in case you forgot to sudo
cmap w!! %!sudo tee > /dev/null %
